export interface ChangelogEntry {
  date: string; // YYYY-MM-DD (uso interno para ordenar; ya no se muestra)
  version?: string; // p.ej. "v0.12" — se muestra en vez de la fecha en las entradas hechas
  title: string;
  description: string;
  status: "done" | "planned";
}

// Se actualiza a mano con cada tanda de trabajo que se commitea.
// Las entradas más recientes van primero.
export const CHANGELOG: ChangelogEntry[] = [
  {
    date: "2026-07-16",
    version: "v0.56",
    title: "Marcar eventos del Calendario como finalizados",
    description: "En el detalle de un día, cada evento tiene un círculo que al pulsarlo lo marca como finalizado (se pone verde con un check, el título se tacha) sin tener que editar el evento. Se refleja también en las píldoras del mes.",
    status: "done",
  },
  {
    date: "2026-07-16",
    version: "v0.55",
    title: "Arreglo: los eventos del Calendario \"desaparecían\" tras crearlos",
    description: "A la tabla events_personnel le faltaba la foreign key hacia personnel (y lo mismo le pasaba a tickets_contacts y tasks_personnel con contacts/personnel). Sin esa relación, Supabase no podía resolver la consulta del Calendario/Tickets/Tablero y, al fallar, vaciaba toda la lista en cada recarga: el evento se creaba bien, pero no se veía. Añadidas las 3 foreign keys que faltaban, y ahora si algún catálogo falla al cargar sale un aviso en vez de vaciarse en silencio.",
    status: "done",
  },
  {
    date: "2026-07-16",
    version: "v0.54",
    title: "Rediseño del Calendario",
    description: "Nuevo panel lateral con \"Hoy\" (eventos del día con su hora) y \"Esta semana\" (Producción/Reuniones/Vacaciones-teletrabajo), leyenda de colores fija y contador de eventos del mes. Los eventos ahora admiten hora de inicio y de fin (opcional), visibles en las píldoras del mes y en el detalle del día.",
    status: "done",
  },
  {
    date: "2026-07-15",
    version: "v0.53",
    title: "Rediseño del Panel",
    description: "Los 8 KPI llevan ahora un icono y ya no muestran un % de variación inventado (no había datos históricos para calcularlo de verdad). Cabecera con \"actualizado hace X min\". Forecast con el total sumado, \"Pipeline por etapa\" restyleado y un hueco para \"Décimas\" (subidas/bajadas) marcado como Próximamente, a la espera de traer los datos reales de Jaippy.",
    status: "done",
  },
  {
    date: "2026-07-15",
    version: "v0.52",
    title: "Rediseño de \"Mi día\"",
    description: "Cabecera con saludo, resumen del día y \"tu foco de hoy\" (el pendiente más urgente entre negocios, tickets y tareas), y 4 tarjetas con mis tareas, el calendario de hoy, tickets urgentes y negocios por cerrar.",
    status: "done",
  },
  {
    date: "2026-07-15",
    version: "v0.51",
    title: "Color en los modelos de facturación",
    description: "Cada modelo de facturación tiene un color asignado automáticamente, visible como chip en Negocios y en Ajustes.",
    status: "done",
  },
  {
    date: "2026-07-15",
    version: "v0.50",
    title: "Vista previa y nota rápida con color en las tarjetas de Negocio",
    description: "Un botón de ojo abre un panel lateral con el contacto, los hoteles y el historial del negocio sin salir del tablero. Otro botón permite dejar una nota rápida con un color a elegir, visible directamente en la tarjeta.",
    status: "done",
  },
  {
    date: "2026-07-15",
    version: "v0.49",
    title: "Listas de contactos",
    description: "En Contactos se pueden seleccionar varios (checkboxes en la tabla) y añadirlos a una lista nueva o existente, para agrupar contactos más allá de la etiqueta o el estado.",
    status: "done",
  },
  {
    date: "2026-07-15",
    version: "v0.48",
    title: "Aviso de correo duplicado al crear un contacto",
    description: "Al escribir un email que ya existe en otro contacto, la ficha avisa antes de guardar.",
    status: "done",
  },
  {
    date: "2026-07-15",
    version: "v0.47",
    title: "Filtro por etiqueta en Contactos",
    description: "Nuevo desplegable para filtrar contactos por etiqueta, combinable con el filtro de estado y la búsqueda.",
    status: "done",
  },
  {
    date: "2026-07-15",
    version: "v0.46",
    title: "Importación real de Contactos desde HubSpot",
    description: "15.619 contactos importados desde la exportación de HubSpot (email como clave para no duplicar en futuras importaciones). Si faltaba el nombre se usa la parte del correo antes de la @, y el estado de lead por defecto queda en \"Lead\". Se enlazaron 7.971 contactos con su empresa por nombre.",
    status: "done",
  },
  {
    date: "2026-07-14",
    version: "v0.45",
    title: "Mismo estilo que Hoteles aplicado a Empresas, e importación real desde HubSpot",
    description: "La vista de Empresas usa ya las mismas tarjetas, avatar y pestañas que Hoteles. Además se importaron 19.970 empresas reales desde la exportación de HubSpot; la relación \"cliente\" sale del campo \"Jaippy - Es cliente\", no de \"Cliente actual\".",
    status: "done",
  },
  {
    date: "2026-07-14",
    version: "v0.44",
    title: "Rediseño de Hoteles (tarjetas y lista)",
    description: "Nuevas tarjetas con avatar, borde azul si es cliente, nota (IJ) con más peso visual, estrellas, ciudad y equipo asignado; los botones de editar/borrar se movieron abajo a la derecha. La vista de lista sigue el mismo criterio.",
    status: "done",
  },
  {
    date: "2026-07-14",
    version: "v0.43",
    title: "Importación real de Hoteles desde Jaippy",
    description: "12.807 hoteles (todos, no solo los clientes) importados directamente desde la base de datos operativa de Jaippy: nombre, TAU, cliente, última IJ, booking, PMS, categoría, estrellas, ciudad, dirección y descripción.",
    status: "done",
  },
  {
    date: "2026-07-13",
    version: "v0.42",
    title: "Fin del concepto de \"década/plan\" en Hoteles",
    description: "has_plan pasa a llamarse is_client (Cliente) y se eliminan current_tenth, contracted_tenths, remaining_tenths, deviation_days, deviation_pct, plan_end_date e invoiced: eran datos de un \"plan\" que ya no existe. Se quitó también el panel \"Desviación de planes\" del Panel y la tarjeta \"Fin de plan urgente\" de Cartera activa.",
    status: "done",
  },
  {
    date: "2026-07-13",
    version: "v0.41",
    title: "El scroll horizontal de las tablas ya no queda escondido abajo del todo",
    description: "En tablas largas, la barra de scroll horizontal aparecía solo al final de la tabla, obligando a bajar del todo para moverla. Ahora es más accesible.",
    status: "done",
  },
  {
    date: "2026-07-13",
    version: "v0.40",
    title: "Campos que faltaban en el modelo de datos",
    description: "Se completaron los campos que faltaban en Contacto, Hotel y Negocio (apellidos y móvil en contactos, habitaciones/ADR/booking/estrellas/categoría/cadena/PMS/ciudad/código postal/dirección/descripción en hoteles, campos legales y de contrato en negocios), manteniendo los campos ya existentes.",
    status: "done",
  },
  {
    date: "2026-07-09",
    version: "v0.39",
    title: "Fusionar duplicados de verdad",
    description: "En Ajustes, cada grupo de duplicados tiene un botón \"Fusionar\": eliges qué valor de cada campo quieres conservar (o lo escribes tú), y al confirmar se guarda en un único registro, se mueven sus vínculos (empresas, negocios, tickets, etiquetas...) y se borran los duplicados.",
    status: "done",
  },
  {
    date: "2026-07-09",
    title: "Eliminar un Usuario ahora revoca el acceso de verdad",
    description: "Antes, borrar a alguien de Usuarios solo quitaba su ficha; su cuenta seguía activa y podía seguir entrando. Ahora también se elimina su cuenta real. Requiere la Edge Function delete-user desplegada en Supabase.",
    status: "planned",
  },
  {
    date: "2026-07-09",
    version: "v0.38",
    title: "Negocios perdidos, archivados en vez de columna",
    description: "Se quitó \"Perdido\" del tablero (ya no hay que verlo entre las etapas activas). Junto a \"Nuevo negocio\" hay un botón \"Archivados\" con los negocios perdidos, por si hay que reabrirlos o borrarlos.",
    status: "done",
  },
  {
    date: "2026-07-09",
    version: "v0.37",
    title: "Panel: orden nuevo y cuadros accionables",
    description: "Los 8 cuadros del Panel siguen el orden: pipeline abierto, ingresos mes actual, ingresos estimados este mes, ingresos mes a futuro, cambios en la fecha, hoteles con plan, contactos, ingresos ganados. Y ahora son clicables: te llevan directo al módulo de donde sale ese dato.",
    status: "done",
  },
  {
    date: "2026-07-09",
    version: "v0.36",
    title: "Sin emojis: iconos SVG en su lugar",
    description: "Se quitaron los emojis (⏳ 📅 ↻ ✉) de las tarjetas de negocio/hotel, el indicador de recurrencia y el botón de correo, sustituidos por iconos SVG del mismo estilo que el resto de la app.",
    status: "done",
  },
  {
    date: "2026-07-09",
    version: "v0.35",
    title: "Retoques varios",
    description: "El umbral de \"en riesgo\" en Cartera activa pasó de 5 a 3 meses de desviación. \"Década\" ahora dice \"Décima\". Los Tickets ya se pueden eliminar desde su ficha, como el resto de entidades.",
    status: "done",
  },
  {
    date: "2026-07-09",
    version: "v0.34",
    title: "Filtros y exportar a CSV en Contactos, Empresas y Hoteles",
    description: "Cada vista tiene un desplegable de filtro (estado del lead / relación cliente / plan) que se combina con la búsqueda, y un botón \"Exportar CSV\" que descarga exactamente lo filtrado, solo con las columnas que tengas visibles en \"Columnas\".",
    status: "done",
  },
  {
    date: "2026-07-09",
    version: "v0.33",
    title: "Arreglo: los contactos vinculados no se veían en la ficha de empresa",
    description: "La tarjeta de empresa ya mostraba el número de contactos asociados, pero al abrir la ficha no aparecían. Ahora la ficha de empresa lista los contactos vinculados (con su cargo) y enlaza a cada uno.",
    status: "done",
  },
  {
    date: "2026-07-09",
    version: "v0.32",
    title: "El logo de divisual vuelve al Panel",
    description: "Al hacer clic en \"divisual\" arriba a la izquierda, ahora te lleva al Panel, como en cualquier app.",
    status: "done",
  },
  {
    date: "2026-07-09",
    title: "Usuarios (antes \"Personal\") ligado a cuentas reales",
    description: "Se renombró Personal a Usuarios y se movió debajo de Changelog. Nueva tabla `profiles`, sincronizada con auth.users por trigger (el navegador no puede leer auth.users directamente), para saber quién tiene cuenta de verdad. El Chat y el filtro por persona del Calendario ya solo muestran usuarios con cuenta, no todo el directorio de Personal.",
    status: "planned",
  },
  {
    date: "2026-07-09",
    version: "v0.31",
    title: "Categorías del Calendario según la pestaña",
    description: "Antes se podía crear una \"Reunión\" desde la pestaña Vacaciones. Ahora el desplegable de categoría solo ofrece las que tienen sentido en la pestaña activa (Vista técnica → Despliegue; Eventos → Reunión/Formación/Visita a hotel; Vacaciones y teletrabajo → Vacaciones/Teletrabajo).",
    status: "done",
  },
  {
    date: "2026-07-09",
    version: "v0.30",
    title: "Arreglo: \"Panel\" siempre aparecía marcado en el menú",
    description: "El enlace de Panel usaba la clase de \"activo\" no exacta, que en Vue Router coincide con cualquier ruta (porque todas cuelgan de \"/\"). Se cambió a la clase de coincidencia exacta.",
    status: "done",
  },
  {
    date: "2026-07-09",
    title: "Esquema SQL consolidado en un solo archivo",
    description: "Todos los sql/*.sql anteriores (10 archivos sueltos, más las tablas base que nunca estaban en el repo) se han unido en sql/2026-07-09_schema_completo.sql: crea toda la base de datos desde cero, en el estado final que espera la app. Pensado para borrar y rehacer la base de datos.",
    status: "planned",
  },
  {
    date: "2026-07-09",
    title: "Notificaciones en tiempo real",
    description: "Aviso al momento (sin recargar) cuando te llega un mensaje nuevo en el Chat o te asignan una tarea en el Tablero. Requiere sql/2026-07-09_schema_completo.sql (el Chat ya tenía Realtime activado; ese archivo añade la parte que falta para las asignaciones de tareas).",
    status: "planned",
  },
  {
    date: "2026-07-09",
    version: "v0.29",
    title: "Vista imprimible de propuesta de negocio",
    description: "Botón \"Ver propuesta\" en la ficha de un negocio: abre una página limpia (sin menú) con los datos del negocio, lista para imprimir o guardar como PDF desde el navegador.",
    status: "done",
  },
  {
    date: "2026-07-09",
    version: "v0.28",
    title: "Botón de correo en Contactos",
    description: "Junto al email de un contacto hay un botón que abre tu cliente de correo con el destinatario ya puesto, y lo apunta en el historial del contacto.",
    status: "done",
  },
  {
    date: "2026-07-09",
    version: "v0.27",
    title: "Forecast de ingresos en el Panel",
    description: "Gráfico de barras con los ingresos previstos (negocios ganados) de los próximos 12 meses, con detalle al pasar el ratón y una vista en tabla.",
    status: "done",
  },
  {
    date: "2026-07-09",
    version: "v0.26",
    title: "Detectar duplicados",
    description: "Nueva herramienta en Ajustes: busca contactos con el mismo correo y empresas con el mismo nombre, y enlaza a cada ficha para revisarlas y fusionarlas a mano.",
    status: "done",
  },
  {
    date: "2026-07-09",
    version: "v0.25",
    title: "Semáforo de riesgo en Cartera activa",
    description: "La pestaña \"Tickets activos\" muestra un nivel de riesgo (alto/medio/bajo) por hotel, combinando la desviación del plan con los tickets abiertos.",
    status: "done",
  },
  {
    date: "2026-07-09",
    version: "v0.24",
    title: "\"Vence pronto\" en Negocios y Hoteles",
    description: "Un negocio abierto con cierre previsto en menos de 15 días, o un hotel con plan que termina en menos de 30, se marca en su tarjeta.",
    status: "done",
  },
  {
    date: "2026-07-09",
    version: "v0.23",
    title: "Buscador universal (Ctrl/Cmd+K)",
    description: "Desde cualquier pantalla, Ctrl+K abre un buscador que encuentra contactos, empresas, hoteles, negocios, tareas, tickets y personal, y te lleva directo a la ficha.",
    status: "done",
  },
  {
    date: "2026-07-09",
    version: "v0.22",
    title: "Mi día",
    description: "Nueva pantalla (arriba en General): mis tareas abiertas del Tablero, eventos de hoy en el Calendario, tickets urgentes (vencen en 15 días) y negocios por cerrar esta semana, todo junto al abrir la app.",
    status: "done",
  },
  {
    date: "2026-07-09",
    title: "Negocios estancados y alertas de desviación",
    description: "Un negocio abierto que lleva más de 14 días en la misma etapa se marca en Negocios (⏳ y borde de aviso). Al entrar en la app, si algún hotel con plan se ha desviado más de un 15%, sale un aviso. Requiere sql/2026-07-09_schema_completo.sql para el histórico de etapa.",
    status: "planned",
  },
  {
    date: "2026-07-09",
    title: "Invitar usuarios desde Ajustes",
    description: "Nueva tarjeta \"Usuarios del equipo\": pones el correo (y nombre opcional) y le llega una invitación para poner su contraseña y entrar al CRM. La creación real la hace una Edge Function de Supabase (supabase/functions/invite-user) con la clave service_role, que nunca toca el navegador.",
    status: "planned",
  },
  {
    date: "2026-07-09",
    version: "v0.21",
    title: "Nuevos KPI de ingresos en el Panel",
    description: "Segunda fila de 4 cuadros: negocios con cierre movido este mes, ingresos estimados este mes (pipeline abierto que cierra este mes), ingresos del mes actual (negocios ganados con servicio activo) e ingresos a futuro (servicio que empieza más adelante). Requiere el trigger de sql/2026-07-09_schema_completo.sql para registrar cuándo cambia la fecha de cierre.",
    status: "done",
  },
  {
    date: "2026-07-09",
    version: "v0.20",
    title: "Etiquetas nuevas al vuelo en Contactos",
    description: "En la ficha de un contacto ya se puede crear una etiqueta nueva sin salir del formulario, igual que en las tareas del Tablero.",
    status: "done",
  },
  {
    date: "2026-07-09",
    version: "v0.19",
    title: "Borrar modelos de facturación",
    description: "En Ajustes, cada modelo de facturación tiene ahora un botón para eliminarlo.",
    status: "done",
  },
  {
    date: "2026-07-09",
    version: "v0.18",
    title: "Categorías \"Formación\" y \"Visita a hotel\" en el Calendario",
    description: "Dos categorías nuevas en la pestaña Eventos, junto a Reunión.",
    status: "done",
  },
  {
    date: "2026-07-09",
    version: "v0.17",
    title: "Recurrencia en Calendario y Tablero",
    description: "Los eventos y las tareas admiten repetición semanal (elige el día) o mensual (elige el día del mes). Un evento recurrente se proyecta en todos los meses sin duplicar filas; una tarea recurrente, al llegar a \"Listo en prod\", vuelve sola a \"Por hacer\" con la fecha de la próxima ocurrencia.",
    status: "done",
  },
  {
    date: "2026-07-09",
    version: "v0.16",
    title: "Calendario: líneas y ancho",
    description: "La cuadrícula tenía bordes dobles entre días y se estiraba demasiado en pantallas anchas. Ahora tiene un único borde limpio, esquinas redondeadas, el día de hoy resaltado y un ancho máximo para que las celdas no queden deformadas.",
    status: "done",
  },
  {
    date: "2026-07-09",
    version: "v0.15",
    title: "Borrar un negocio",
    description: "La ficha de un negocio tenía botón para guardar pero no para eliminarlo. Ya se puede borrar desde el mismo modal, como en el resto de fichas.",
    status: "done",
  },
  {
    date: "2026-07-09",
    version: "v0.14",
    title: "Ancho de Contactos, Empresas, Personal y Hoteles",
    description: "Estas vistas usaban solo una franja central del ancho disponible; ahora aprovechan todo el espacio, igual que Negocios o Tablero.",
    status: "done",
  },
  {
    date: "2026-07-09",
    version: "v0.13",
    title: "Desplegables más redondeados",
    description: "Se aumentó el radio de los selectores y menús propios de la app (buscadores, filtros, formularios). El menú nativo que despliega un <select> lo pinta el sistema operativo y no se puede redondear por CSS.",
    status: "done",
  },
  {
    date: "2026-07-09",
    version: "v0.12",
    title: "Arreglar mensajes de error genéricos",
    description: "El aviso de error mostraba \"[object Object]\" en vez del mensaje real cuando Supabase devolvía un error. Ahora se extrae el mensaje de verdad.",
    status: "done",
  },
  {
    date: "2026-07-09",
    title: "Ejecutar el SQL de recurrencia en Supabase",
    description: "Faltan las columnas recurrence y recurrence_day en events y tasks (sql/2026-07-09_schema_completo.sql) para que funcione la repetición.",
    status: "planned",
  },
  {
    date: "2026-07-08",
    version: "v0.11",
    title: "Backlog y etiquetas en el Tablero",
    description: "Pestaña Backlog: todas las tareas nacen sin sprint y se agrupan por sprint (o Backlog) con un desplegable para moverlas y cambiar su etapa. Etiquetas de color creables al vuelo y asignables a cualquier tarea.",
    status: "done",
  },
  {
    date: "2026-07-08",
    version: "v0.10",
    title: "Sprints, subtareas y adjuntos en el Tablero",
    description: "Sprints con fecha de inicio/fin y filtro en el tablero, checklist de subtareas dentro de cada tarea, y adjuntar enlaces (documentos, capturas...) a la ficha de la tarea.",
    status: "done",
  },
  {
    date: "2026-07-08",
    version: "v0.9",
    title: "Prioridad y fecha límite en el Tablero",
    description: "Cada tarea tiene ahora prioridad (Alta/Media/Baja, con color en el borde de la tarjeta) y fecha límite (en rojo si está vencida).",
    status: "done",
  },
  {
    date: "2026-07-08",
    version: "v0.8",
    title: "Importación de Hoteles desde Jaippy + seguimiento de década",
    description: "Script para traer name/tau/has_plan/plan_end_date/deviation_days/current_ij desde la base de datos de Jaippy. Nuevo: last_known_tenth, last_tenth_check_at y tenth_increased para saber qué hoteles suben o bajan de década entre ejecuciones (flecha ▲▼ en Cartera activa).",
    status: "done",
  },
  {
    date: "2026-07-08",
    version: "v0.7",
    title: "Calendario conjunto",
    description: "Vista técnica (subidas a producción), Eventos (reuniones) y Vacaciones/teletrabajo, con filtro por persona y un roadmap del día al hacer clic en una fecha.",
    status: "done",
  },
  {
    date: "2026-07-08",
    version: "v0.6",
    title: "Chat interno con solicitud de tareas",
    description: "Mensajería 1 a 1 entre personal de la empresa, con un botón para solicitar una tarea dentro de la conversación. El destinatario acepta o rechaza; al aceptar, la tarea se crea automáticamente en el Tablero.",
    status: "done",
  },
  {
    date: "2026-07-08",
    version: "v0.5",
    title: "Changelog / Roadmap",
    description: "Este apartado: lo que llevamos hecho y lo que queda por hacer, visible dentro de la app.",
    status: "done",
  },
  {
    date: "2026-07-08",
    version: "v0.4",
    title: "Cartera activa (Administración/Ventas)",
    description: "Resumen de hoteles cliente con pestañas Resumen y Tickets activos: KPIs, cambios de estado recientes y fin de plan urgente.",
    status: "done",
  },
  {
    date: "2026-07-08",
    version: "v0.3",
    title: "Tablero (Soporte/IT)",
    description: "Kanban de tareas y bugs con historias, asignación a varias personas, filtro por persona y comentarios por tarea.",
    status: "done",
  },
  {
    date: "2026-07-08",
    version: "v0.2",
    title: "Tickets (Customer Success)",
    description: "Nueva división Customer Success con el kanban de Tickets: Por iniciar → Seguimiento activo → Consolidación → Décima alcanzada → Cierre de ciclo.",
    status: "done",
  },
  {
    date: "2026-07-08",
    version: "v0.1",
    title: "Ancho de Negocios y fix de despliegue en Vercel",
    description: "El tablero de Negocios ya usa todo el ancho disponible. Se quitó node_modules del repositorio (causaba el fallo de build en Vercel) y se añadió .gitignore.",
    status: "done",
  },
  {
    date: "2026-07-08",
    title: "Automatizar el paso de etapa por tiempo",
    description: "Trigger para que un ticket pase solo de Consolidación a Décima alcanzada a los 30 días de subir la décima.",
    status: "planned",
  },
];
