-- =====================================================================
-- Divisual — Backlog (usa sprint_id ya existente) + Etiquetas en el Tablero
-- Ejecutar en Supabase → SQL Editor → New query → Run.
-- Requiere que ya exista la tabla `tasks` y `sprints`
-- (ver 2026-07-08_tablero_jira_extra.sql).
-- =====================================================================

create table if not exists labels (
  id    bigint generated by default as identity primary key,
  name  text not null,
  color text not null default '#6366f1'
);

create table if not exists tasks_labels (
  id       bigint generated by default as identity primary key,
  task_id  bigint not null references tasks(id) on delete cascade,
  label_id bigint not null references labels(id) on delete cascade
);

create index if not exists idx_tasks_labels_task_id on tasks_labels(task_id);
create index if not exists idx_tasks_labels_label_id on tasks_labels(label_id);

alter table labels enable row level security;
alter table tasks_labels enable row level security;

create policy "authenticated full access" on labels
  for all to authenticated using (true) with check (true);
create policy "authenticated full access" on tasks_labels
  for all to authenticated using (true) with check (true);

-- Nota: el Backlog no es una tabla nueva — son las tareas cuya sprint_id
-- es NULL (ya soportado por el sprint_id que añadió 2026-07-08_tablero_jira_extra.sql).
-- Toda tarea nueva nace sin sprint por defecto, es decir, en el Backlog.
