-- =====================================================================
-- Divisual — Esquema completo consolidado
-- Sustituye a todos los archivos sql/2026-07-08_*.sql y sql/2026-07-09_*.sql
-- anteriores (se han borrado del repo). Este único archivo crea TODA la
-- base de datos desde cero, en el estado final que espera el código de
-- la app hoy.
--
-- Cómo usarlo:
--   1. (Recomendado) Descomenta y ejecuta primero el PASO 0 para borrar
--      las tablas existentes — así partes de verdad de cero. Si te
--      saltas este paso y ya tenías alguna tabla de antes, el PASO 2.5
--      añade las columnas que le falten sin tocar las que ya tenga.
--   2. Ejecuta el resto de este archivo completo en Supabase → SQL
--      Editor → New query → Run.
--   3. Vuelve a insertar tus datos (los tienes respaldados aparte).
--   4. Si usas la importación automática de Hoteles desde Jaippy, mira
--      la nota al final del archivo — es un script operativo distinto,
--      no forma parte de la creación del esquema.
--
-- Notas de reconstrucción (columnas que no estaban en ningún sql/*.sql
-- de este repo porque venían del script original divisual-backend.sql,
-- que no está en el repositorio — se han reconstruido a partir de los
-- tipos de src/lib/types.ts y de cómo los usa la app):
--   contacts, companies, contacts_companies, contacts_historial,
--   personnel_historial, tags, tags_contacts, deals (columnas base),
--   deals_hotels, hotels (columnas base), personnel, hotels_personnel.
--
-- Además incluye `profiles`: una copia mínima (id/email) de auth.users,
-- mantenida por trigger, porque el navegador no puede leer auth.users
-- directamente. Es lo que usan Usuarios, el Chat y el filtro por
-- persona del Calendario para saber quién tiene cuenta de verdad.
-- =====================================================================


-- ---------------------------------------------------------------------
-- PASO 0 (opcional, DESTRUCTIVO) — borrar todo lo existente primero.
-- Descomenta este bloque solo si quieres que este script también borre
-- las tablas actuales. Si prefieres borrarlas tú a mano desde Supabase,
-- déjalo comentado y salta directamente al PASO 1.
-- ---------------------------------------------------------------------
-- drop table if exists profiles cascade;
-- drop trigger if exists trg_handle_new_auth_user on auth.users;
-- drop function if exists handle_new_auth_user();
-- drop table if exists messages cascade;
-- drop table if exists tasks_labels cascade;
-- drop table if exists task_attachments cascade;
-- drop table if exists task_subitems cascade;
-- drop table if exists task_comments cascade;
-- drop table if exists tasks_personnel cascade;
-- drop table if exists tasks cascade;
-- drop table if exists tickets_contacts cascade;
-- drop table if exists tickets cascade;
-- drop table if exists deals_hotels cascade;
-- drop table if exists deals cascade;
-- drop table if exists events_personnel cascade;
-- drop table if exists hotels_personnel cascade;
-- drop table if exists tags_contacts cascade;
-- drop table if exists personnel_historial cascade;
-- drop table if exists contacts_historial cascade;
-- drop table if exists contacts_companies cascade;
-- drop table if exists events cascade;
-- drop table if exists labels cascade;
-- drop table if exists sprints cascade;
-- drop table if exists stories cascade;
-- drop table if exists hotels cascade;
-- drop table if exists billing_models cascade;
-- drop table if exists tags cascade;
-- drop table if exists contacts cascade;
-- drop table if exists companies cascade;
-- drop table if exists personnel cascade;


-- ---------------------------------------------------------------------
-- PASO 1 — Tablas base (sin dependencias entre ellas)
-- ---------------------------------------------------------------------

create table if not exists personnel (
  id    bigint generated by default as identity primary key,
  name  text not null,
  email text,
  phone text
);

create table if not exists companies (
  id       bigint generated by default as identity primary key,
  name     text not null,
  phone    text,
  client   boolean not null default false,
  category text
);

create table if not exists contacts (
  id            bigint generated by default as identity primary key,
  name          text not null,
  phone         text,
  email         text,
  lead_status   text not null default 'Lead', -- 'Lead' | 'Oportunidad' | 'Cliente' | 'Inactivo'
  creation_date timestamptz not null default now(),
  last_update   timestamptz default now(),
  created_by    uuid references auth.users(id) default auth.uid()
);

create table if not exists tags (
  id   bigint generated by default as identity primary key,
  name text not null
);

create table if not exists billing_models (
  id   bigint generated by default as identity primary key,
  name text not null
);

create table if not exists hotels (
  id                   bigint generated by default as identity primary key,
  name                 text not null unique,
  has_plan             boolean not null default false,
  tau                  numeric,
  contracted_tenths    numeric,
  current_ij           numeric,
  objective            numeric,
  deviation_days       integer,
  deviation_pct        numeric,
  current_tenth        numeric,
  remaining_tenths     numeric,
  invoiced             boolean not null default false,
  plan_end_date        date,
  updated_at           timestamptz,
  last_known_tenth     numeric,
  last_tenth_check_at  timestamptz,
  tenth_increased      boolean
);

create table if not exists stories (
  id   bigint generated by default as identity primary key,
  name text not null
);

create table if not exists sprints (
  id         bigint generated by default as identity primary key,
  name       text not null,
  start_date date,
  end_date   date,
  active     boolean not null default true
);

create table if not exists labels (
  id    bigint generated by default as identity primary key,
  name  text not null,
  color text not null default '#6366f1'
);

create table if not exists events (
  id           bigint generated by default as identity primary key,
  title        text not null,
  description  text,
  category     text not null, -- 'Despliegue' | 'Reunión' | 'Vacaciones' | 'Teletrabajo' | 'Formación' | 'Visita a hotel'
  start_date   date not null,
  end_date     date, -- sin repetición: fin del evento (opcional) · con repetición: "repetir hasta" (opcional)
  recurrence   text, -- 'weekly' | 'monthly' | null
  recurrence_day smallint, -- semanal: 1(Lun)-7(Dom) · mensual: 1-31
  created_by   uuid references auth.users(id) default auth.uid(),
  created_at   timestamptz not null default now()
);


-- ---------------------------------------------------------------------
-- PASO 2 — Tablas de relación y tablas que dependen de las anteriores
-- ---------------------------------------------------------------------

create table if not exists contacts_companies (
  id         bigint generated by default as identity primary key,
  contact_id bigint not null references contacts(id) on delete cascade,
  company_id bigint not null references companies(id) on delete cascade,
  role       text
);

create table if not exists contacts_historial (
  id         bigint generated by default as identity primary key,
  contact_id bigint not null references contacts(id) on delete cascade,
  created_by uuid references auth.users(id) default auth.uid(),
  created_at timestamptz not null default now(),
  note       text
);

create table if not exists personnel_historial (
  id           bigint generated by default as identity primary key,
  personnel_id bigint not null references personnel(id) on delete cascade,
  created_by   uuid references auth.users(id) default auth.uid(),
  created_at   timestamptz not null default now(),
  note         text
);

-- Ojo: la columna que apunta a `tags` se llama igual que la tabla
-- (no "tag_id") porque así la usa el código (ver ContactModal.vue).
create table if not exists tags_contacts (
  id         bigint generated by default as identity primary key,
  contact_id bigint not null references contacts(id) on delete cascade,
  tags       bigint not null references tags(id) on delete cascade,
  created_by uuid references auth.users(id) default auth.uid()
);

-- Ojo: columnas id_hotel / id_personnel (no hotel_id / personnel_id)
-- porque así las usa el código (ver HotelModal.vue).
create table if not exists hotels_personnel (
  id           bigint generated by default as identity primary key,
  id_hotel     bigint not null references hotels(id) on delete cascade,
  id_personnel bigint not null references personnel(id) on delete cascade,
  role         text,
  area         text
);

create table if not exists events_personnel (
  id           bigint generated by default as identity primary key,
  event_id     bigint not null references events(id) on delete cascade,
  personnel_id bigint not null references personnel(id) on delete cascade
);

create table if not exists deals (
  id                       bigint generated by default as identity primary key,
  name                     text not null,
  status                   text not null default 'Prospecto', -- ver DEAL_STAGES en lib/types.ts
  closing_date             date,
  value                    numeric,
  type_of_charge           text, -- 'Mensual' | 'Trimestral' | 'Anual' | 'Pago único'
  start_date               date,
  end_date                 date,
  contact_id               bigint references contacts(id) on delete set null,
  billing_model            bigint references billing_models(id) on delete set null,
  closing_date_prev        date,
  closing_date_changed_at  timestamptz,
  status_prev              text,
  status_changed_at        timestamptz not null default now(),
  created_by               uuid references auth.users(id) default auth.uid()
);

create table if not exists deals_hotels (
  id       bigint generated by default as identity primary key,
  deal_id  bigint not null references deals(id) on delete cascade,
  hotel_id bigint not null references hotels(id) on delete cascade
);

create table if not exists tickets (
  id            bigint generated by default as identity primary key,
  title         text not null,
  status        text, -- ver TICKET_STAGES en lib/types.ts
  plan_end_date date,
  company_id    bigint references companies(id) on delete set null,
  owner_id      bigint references personnel(id) on delete set null,
  hotel_id      bigint references hotels(id) on delete set null,
  created_by    uuid references auth.users(id) default auth.uid(),
  created_at    timestamptz not null default now()
);

create table if not exists tickets_contacts (
  id         bigint generated by default as identity primary key,
  ticket_id  bigint not null references tickets(id) on delete cascade,
  contact_id bigint not null references contacts(id) on delete cascade
);

create table if not exists tasks (
  id             bigint generated by default as identity primary key,
  title          text not null,
  description    text,
  type           text, -- 'Tarea' | 'Bug'
  status         text, -- ver TASK_STAGES en lib/types.ts
  priority       text, -- 'Alta' | 'Media' | 'Baja'
  due_date       date,
  story_id       bigint references stories(id) on delete set null,
  sprint_id      bigint references sprints(id) on delete set null,
  recurrence     text, -- 'weekly' | 'monthly' | null
  recurrence_day smallint, -- semanal: 1(Lun)-7(Dom) · mensual: 1-31
  created_by     uuid references auth.users(id) default auth.uid(),
  created_at     timestamptz not null default now()
);

create table if not exists tasks_personnel (
  id           bigint generated by default as identity primary key,
  task_id      bigint not null references tasks(id) on delete cascade,
  personnel_id bigint not null references personnel(id) on delete cascade
);

create table if not exists task_comments (
  id           bigint generated by default as identity primary key,
  task_id      bigint not null references tasks(id) on delete cascade,
  author_email text,
  comment      text not null,
  created_at   timestamptz not null default now()
);

create table if not exists task_subitems (
  id         bigint generated by default as identity primary key,
  task_id    bigint not null references tasks(id) on delete cascade,
  title      text not null,
  done       boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists task_attachments (
  id         bigint generated by default as identity primary key,
  task_id    bigint not null references tasks(id) on delete cascade,
  label      text not null,
  url        text not null,
  created_at timestamptz not null default now()
);

create table if not exists tasks_labels (
  id       bigint generated by default as identity primary key,
  task_id  bigint not null references tasks(id) on delete cascade,
  label_id bigint not null references labels(id) on delete cascade
);

create table if not exists messages (
  id               bigint generated by default as identity primary key,
  sender_email     text not null,
  recipient_email  text not null,
  body             text,
  type             text not null default 'text', -- 'text' | 'task_request'
  task_title       text,
  task_description text,
  task_type        text,
  task_response    text, -- 'pending' | 'accepted' | 'declined', solo para type = 'task_request'
  task_id          bigint references tasks(id) on delete set null,
  created_at       timestamptz not null default now()
);


-- ---------------------------------------------------------------------
-- PASO 2.5 — Red de seguridad: si alguna de estas tablas ya existía de
-- una ejecución parcial anterior (por ejemplo, no se pasó por el PASO 0
-- para borrarlo todo primero), "create table if not exists" no la toca
-- y le pueden faltar columnas que se añadieron más tarde en el
-- historial original. Esto las añade sin tocar las que ya tenga.
-- ---------------------------------------------------------------------
alter table hotels add column if not exists remaining_tenths numeric;
alter table hotels add column if not exists invoiced boolean not null default false;
alter table hotels add column if not exists updated_at timestamptz;
alter table hotels add column if not exists last_known_tenth numeric;
alter table hotels add column if not exists last_tenth_check_at timestamptz;
alter table hotels add column if not exists tenth_increased boolean;

alter table tasks add column if not exists priority text;
alter table tasks add column if not exists due_date date;
alter table tasks add column if not exists sprint_id bigint references sprints(id) on delete set null;
alter table tasks add column if not exists recurrence text;
alter table tasks add column if not exists recurrence_day smallint;

alter table deals add column if not exists closing_date_prev date;
alter table deals add column if not exists closing_date_changed_at timestamptz;
alter table deals add column if not exists status_prev text;
alter table deals add column if not exists status_changed_at timestamptz not null default now();

alter table events add column if not exists recurrence text;
alter table events add column if not exists recurrence_day smallint;


-- ---------------------------------------------------------------------
-- PASO 2.6 — Usuarios reales (los que pueden iniciar sesión), a partir
-- de auth.users. El cliente (el navegador) no puede leer auth.users
-- directamente — ni con RLS — así que se refleja solo lo imprescindible
-- (id, email, fecha de alta) en esta tabla mediante un trigger, que es
-- el patrón recomendado por Supabase para esto. Sirve para distinguir,
-- dentro de `personnel`, quién tiene cuenta de verdad (Usuarios, Chat,
-- filtro por persona del Calendario) de quién es solo un contacto de
-- directorio sin acceso a la app.
-- ---------------------------------------------------------------------

create table if not exists profiles (
  id         uuid primary key references auth.users(id) on delete cascade,
  email      text not null,
  created_at timestamptz not null default now()
);


-- ---------------------------------------------------------------------
-- PASO 3 — Índices
-- ---------------------------------------------------------------------

create index if not exists idx_contacts_companies_contact_id on contacts_companies(contact_id);
create index if not exists idx_contacts_companies_company_id on contacts_companies(company_id);
create index if not exists idx_contacts_historial_contact_id on contacts_historial(contact_id);
create index if not exists idx_personnel_historial_personnel_id on personnel_historial(personnel_id);
create index if not exists idx_tags_contacts_contact_id on tags_contacts(contact_id);
create index if not exists idx_tags_contacts_tags on tags_contacts(tags);
create index if not exists idx_hotels_personnel_id_hotel on hotels_personnel(id_hotel);
create index if not exists idx_hotels_personnel_id_personnel on hotels_personnel(id_personnel);
create index if not exists idx_events_start_date on events(start_date);
create index if not exists idx_events_category on events(category);
create index if not exists idx_events_personnel_event_id on events_personnel(event_id);
create index if not exists idx_events_personnel_personnel_id on events_personnel(personnel_id);

create index if not exists idx_deals_contact_id on deals(contact_id);
create index if not exists idx_deals_billing_model on deals(billing_model);
create index if not exists idx_deals_hotels_deal_id on deals_hotels(deal_id);
create index if not exists idx_deals_hotels_hotel_id on deals_hotels(hotel_id);

create index if not exists idx_tickets_company_id on tickets(company_id);
create index if not exists idx_tickets_owner_id on tickets(owner_id);
create index if not exists idx_tickets_hotel_id on tickets(hotel_id);
create index if not exists idx_tickets_contacts_ticket_id on tickets_contacts(ticket_id);
create index if not exists idx_tickets_contacts_contact_id on tickets_contacts(contact_id);

create index if not exists idx_tasks_story_id on tasks(story_id);
create index if not exists idx_tasks_sprint_id on tasks(sprint_id);
create index if not exists idx_tasks_personnel_task_id on tasks_personnel(task_id);
create index if not exists idx_tasks_personnel_personnel_id on tasks_personnel(personnel_id);
create index if not exists idx_task_comments_task_id on task_comments(task_id);
create index if not exists idx_task_subitems_task_id on task_subitems(task_id);
create index if not exists idx_task_attachments_task_id on task_attachments(task_id);
create index if not exists idx_tasks_labels_task_id on tasks_labels(task_id);
create index if not exists idx_tasks_labels_label_id on tasks_labels(label_id);

create index if not exists idx_messages_sender_email on messages(sender_email);
create index if not exists idx_messages_recipient_email on messages(recipient_email);
create index if not exists idx_messages_created_at on messages(created_at);


-- ---------------------------------------------------------------------
-- PASO 4 — Row Level Security: acceso completo para cualquier usuario
-- autenticado en todas las tablas (mismo criterio en toda la app; no
-- hay registro público, así que no hace falta granularidad por filas).
-- ---------------------------------------------------------------------

do $$
declare
  t text;
begin
  foreach t in array array[
    'personnel', 'companies', 'contacts', 'tags', 'billing_models', 'hotels',
    'stories', 'sprints', 'labels', 'events',
    'contacts_companies', 'contacts_historial', 'personnel_historial',
    'tags_contacts', 'hotels_personnel', 'events_personnel',
    'deals', 'deals_hotels', 'tickets', 'tickets_contacts',
    'tasks', 'tasks_personnel', 'task_comments', 'task_subitems',
    'task_attachments', 'tasks_labels', 'messages', 'profiles'
  ]
  loop
    execute format('alter table %I enable row level security;', t);
    execute format(
      'drop policy if exists "authenticated full access" on %I;', t
    );
    execute format(
      'create policy "authenticated full access" on %I for all to authenticated using (true) with check (true);', t
    );
  end loop;
end $$;


-- ---------------------------------------------------------------------
-- PASO 5 — Triggers
-- ---------------------------------------------------------------------

-- Guarda cuándo cambia la fecha de cierre de un negocio (para el KPI
-- "Cambios en la fecha" del Panel).
create or replace function deals_track_closing_date_change() returns trigger as $$
begin
  if new.closing_date is distinct from old.closing_date then
    new.closing_date_prev := old.closing_date;
    new.closing_date_changed_at := now();
  end if;
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_deals_closing_date_change on deals;
create trigger trg_deals_closing_date_change
  before update on deals
  for each row execute function deals_track_closing_date_change();

-- Guarda cuándo cambia la etapa de un negocio (para detectar negocios
-- "estancados": mucho tiempo sin moverse de etapa).
create or replace function deals_track_status_change() returns trigger as $$
begin
  if new.status is distinct from old.status then
    new.status_prev := old.status;
    new.status_changed_at := now();
  end if;
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_deals_status_change on deals;
create trigger trg_deals_status_change
  before update on deals
  for each row execute function deals_track_status_change();

-- Reconstrucción: mantiene contacts.last_update al día en cada cambio
-- (la app solo lee esta columna; nunca la escribe a mano).
create or replace function contacts_touch_last_update() returns trigger as $$
begin
  new.last_update := now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_contacts_last_update on contacts;
create trigger trg_contacts_last_update
  before update on contacts
  for each row execute function contacts_touch_last_update();

-- Refleja en profiles quién tiene cuenta real (auth.users), sin exponer
-- nada más que id/email/fecha de alta. security definer: los triggers
-- sobre auth.users se ejecutan con el rol interno de Supabase Auth, que
-- no tiene permiso de escritura en public.profiles por sí mismo.
create or replace function handle_new_auth_user() returns trigger as $$
begin
  insert into profiles (id, email) values (new.id, new.email)
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$ language plpgsql security definer set search_path = public;

drop trigger if exists trg_handle_new_auth_user on auth.users;
create trigger trg_handle_new_auth_user
  after insert or update of email on auth.users
  for each row execute function handle_new_auth_user();

-- Rellena profiles con los usuarios que ya existan hoy (no solo los
-- que se creen a partir de ahora).
insert into profiles (id, email, created_at)
select id, email, created_at from auth.users
on conflict (id) do update set email = excluded.email;


-- ---------------------------------------------------------------------
-- PASO 6 — Realtime: para que el Chat y las notificaciones de tareas
-- asignadas lleguen al instante, sin recargar la página.
-- ---------------------------------------------------------------------

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'messages'
  ) then
    alter publication supabase_realtime add table messages;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'tasks_personnel'
  ) then
    alter publication supabase_realtime add table tasks_personnel;
  end if;
end $$;


-- =====================================================================
-- NOTA — Importación de Hoteles desde Jaippy: ver
-- sql/2026-07-14_import_hoteles_jaippy.sql. Esa versión sustituye a la
-- que estaba aquí (solo traía 5 campos y emparejaba por nombre); ahora
-- trae todos los campos comerciales del hotel y empareja por
-- hotels.jaippy_id.
-- =====================================================================
