-- =====================================================================
-- Divisual — Calendario conjunto (técnica, eventos, vacaciones/teletrabajo)
-- Ejecutar en Supabase → SQL Editor → New query → Run.
-- =====================================================================

create table if not exists events (
  id           bigint generated by default as identity primary key,
  title        text not null,
  description  text,
  category     text not null, -- 'Despliegue' | 'Reunión' | 'Vacaciones' | 'Teletrabajo'
  start_date   date not null,
  end_date     date, -- null = evento de un solo día (mismo que start_date)
  created_by   uuid references auth.users(id) default auth.uid(),
  created_at   timestamptz not null default now()
);

create table if not exists events_personnel (
  id           bigint generated by default as identity primary key,
  event_id     bigint not null references events(id) on delete cascade,
  personnel_id bigint not null references personnel(id) on delete cascade
);

create index if not exists idx_events_start_date on events(start_date);
create index if not exists idx_events_category on events(category);
create index if not exists idx_events_personnel_event_id on events_personnel(event_id);
create index if not exists idx_events_personnel_personnel_id on events_personnel(personnel_id);

alter table events enable row level security;
alter table events_personnel enable row level security;

create policy "authenticated full access" on events
  for all to authenticated using (true) with check (true);
create policy "authenticated full access" on events_personnel
  for all to authenticated using (true) with check (true);
