-- =====================================================================
-- Divisual — Sprints, subtareas y adjuntos en el Tablero
-- Ejecutar en Supabase → SQL Editor → New query → Run.
-- Requiere que ya exista la tabla `tasks`.
-- =====================================================================

create table if not exists sprints (
  id         bigint generated by default as identity primary key,
  name       text not null,
  start_date date,
  end_date   date,
  active     boolean not null default true
);

alter table tasks add column if not exists sprint_id bigint references sprints(id) on delete set null;

create table if not exists task_subitems (
  id         bigint generated by default as identity primary key,
  task_id    bigint not null references tasks(id) on delete cascade,
  title      text not null,
  done       boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists task_attachments (
  id         bigint generated by default as identity primary key,
  task_id    bigint not null references tasks(id) on delete cascade,
  label      text not null,
  url        text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_tasks_sprint_id on tasks(sprint_id);
create index if not exists idx_task_subitems_task_id on task_subitems(task_id);
create index if not exists idx_task_attachments_task_id on task_attachments(task_id);

alter table sprints enable row level security;
alter table task_subitems enable row level security;
alter table task_attachments enable row level security;

create policy "authenticated full access" on sprints
  for all to authenticated using (true) with check (true);
create policy "authenticated full access" on task_subitems
  for all to authenticated using (true) with check (true);
create policy "authenticated full access" on task_attachments
  for all to authenticated using (true) with check (true);
