-- =====================================================================
-- Divisual — Tickets (Customer Success), Tablero (Soporte/IT) y
-- Cartera Activa (Administración/Ventas)
-- Ejecutar completo en Supabase → SQL Editor → New query → Run.
-- Es idempotente donde es razonable (IF NOT EXISTS), pero revisa antes
-- de correrlo si ya tienes alguna de estas tablas con otro nombre.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. TICKETS (Customer Success)
-- ---------------------------------------------------------------------
create table if not exists tickets (
  id           bigint generated by default as identity primary key,
  title        text not null,
  status       text,
  plan_end_date date,
  company_id   bigint references companies(id) on delete set null,
  owner_id     bigint references personnel(id) on delete set null,
  hotel_id     bigint references hotels(id) on delete set null,
  created_by   uuid references auth.users(id) default auth.uid(),
  created_at   timestamptz not null default now()
);

create table if not exists tickets_contacts (
  id         bigint generated by default as identity primary key,
  ticket_id  bigint not null references tickets(id) on delete cascade,
  contact_id bigint not null references contacts(id) on delete cascade
);

create index if not exists idx_tickets_company_id on tickets(company_id);
create index if not exists idx_tickets_owner_id on tickets(owner_id);
create index if not exists idx_tickets_hotel_id on tickets(hotel_id);
create index if not exists idx_tickets_contacts_ticket_id on tickets_contacts(ticket_id);
create index if not exists idx_tickets_contacts_contact_id on tickets_contacts(contact_id);

-- ---------------------------------------------------------------------
-- 2. TABLERO (Soporte/IT): historias, tareas, asignaciones, comentarios
-- ---------------------------------------------------------------------
create table if not exists stories (
  id   bigint generated by default as identity primary key,
  name text not null
);

create table if not exists tasks (
  id          bigint generated by default as identity primary key,
  title       text not null,
  description text,
  type        text,
  status      text,
  story_id    bigint references stories(id) on delete set null,
  created_by  uuid references auth.users(id) default auth.uid(),
  created_at  timestamptz not null default now()
);

create table if not exists tasks_personnel (
  id            bigint generated by default as identity primary key,
  task_id       bigint not null references tasks(id) on delete cascade,
  personnel_id  bigint not null references personnel(id) on delete cascade
);

create table if not exists task_comments (
  id           bigint generated by default as identity primary key,
  task_id      bigint not null references tasks(id) on delete cascade,
  author_email text,
  comment      text not null,
  created_at   timestamptz not null default now()
);

create index if not exists idx_tasks_story_id on tasks(story_id);
create index if not exists idx_tasks_personnel_task_id on tasks_personnel(task_id);
create index if not exists idx_tasks_personnel_personnel_id on tasks_personnel(personnel_id);
create index if not exists idx_task_comments_task_id on task_comments(task_id);

-- ---------------------------------------------------------------------
-- 3. CARTERA ACTIVA (Administración/Ventas): columnas nuevas en hotels
-- ---------------------------------------------------------------------
alter table hotels add column if not exists remaining_tenths numeric;
alter table hotels add column if not exists invoiced boolean not null default false;
alter table hotels add column if not exists updated_at timestamptz;

-- ---------------------------------------------------------------------
-- 4. RLS: mismo criterio que el resto del esquema (acceso completo para
--    cualquier usuario autenticado; sin registro público, así que no
--    hace falta granularidad por filas). Ajusta si tu esquema actual
--    usa políticas más restrictivas.
-- ---------------------------------------------------------------------
alter table tickets enable row level security;
alter table tickets_contacts enable row level security;
alter table stories enable row level security;
alter table tasks enable row level security;
alter table tasks_personnel enable row level security;
alter table task_comments enable row level security;

create policy "authenticated full access" on tickets
  for all to authenticated using (true) with check (true);
create policy "authenticated full access" on tickets_contacts
  for all to authenticated using (true) with check (true);
create policy "authenticated full access" on stories
  for all to authenticated using (true) with check (true);
create policy "authenticated full access" on tasks
  for all to authenticated using (true) with check (true);
create policy "authenticated full access" on tasks_personnel
  for all to authenticated using (true) with check (true);
create policy "authenticated full access" on task_comments
  for all to authenticated using (true) with check (true);
