-- =====================================================================
-- Divisual — Chat interno con solicitud de tareas
-- Ejecutar en Supabase → SQL Editor → New query → Run.
-- Requiere que ya exista la tabla `tasks` (ver 2026-07-08_tickets_tablero_cartera.sql).
-- =====================================================================

create table if not exists messages (
  id               bigint generated by default as identity primary key,
  sender_email     text not null,
  recipient_email  text not null,
  body             text,
  type             text not null default 'text', -- 'text' | 'task_request'
  task_title       text,
  task_description text,
  task_type        text,
  task_response    text, -- 'pending' | 'accepted' | 'declined', solo para type = 'task_request'
  task_id          bigint references tasks(id) on delete set null,
  created_at       timestamptz not null default now()
);

create index if not exists idx_messages_sender_email on messages(sender_email);
create index if not exists idx_messages_recipient_email on messages(recipient_email);
create index if not exists idx_messages_created_at on messages(created_at);

alter table messages enable row level security;

create policy "authenticated full access" on messages
  for all to authenticated using (true) with check (true);

-- Habilita la réplica de cambios en tiempo real para que los mensajes
-- aparezcan al instante sin recargar la página.
alter publication supabase_realtime add table messages;
