-- Registro de subidas de décima: cada vez que un ticket entra en la
-- etapa "Décima alcanzada", se guarda una fila (hotel + ticket + fecha) y
-- el ticket vuelve solo a "Seguimiento activo" (un hotel puede volver a
-- subir de décima más adelante, empieza otro ciclo).
create table if not exists hotel_tenth_ups (
  id bigint generated by default as identity primary key,
  hotel_id bigint not null references hotels(id) on delete cascade,
  ticket_id bigint references tickets(id) on delete set null,
  reached_at timestamptz not null default now()
);
create index if not exists idx_hotel_tenth_ups_hotel_id on hotel_tenth_ups(hotel_id);
alter table hotel_tenth_ups enable row level security;
drop policy if exists "authenticated full access" on hotel_tenth_ups;
create policy "authenticated full access" on hotel_tenth_ups for all to authenticated using (true) with check (true);

create or replace function tickets_track_tenth_reached() returns trigger as $$
begin
  if new.status = 'Décima alcanzada' and (tg_op = 'INSERT' or old.status is distinct from new.status) then
    if new.hotel_id is not null then
      insert into hotel_tenth_ups (hotel_id, ticket_id) values (new.hotel_id, new.id);
    end if;
    new.status := 'Seguimiento activo';
  end if;
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_tickets_tenth_reached on tickets;
create trigger trg_tickets_tenth_reached
  before insert or update on tickets
  for each row execute function tickets_track_tenth_reached();

-- Backfill: los tickets que ya estaban en Décima alcanzada antes de este
-- cambio se registran (ya subieron de verdad) y pasan a Seguimiento activo.
insert into hotel_tenth_ups (hotel_id, ticket_id)
select hotel_id, id from tickets where status = 'Décima alcanzada' and hotel_id is not null;
update tickets set status = 'Seguimiento activo' where status = 'Décima alcanzada';

select pg_notify('pgrst', 'reload schema');
