-- =====================================================================
-- Divisual — Campos que faltaban en Contacto, Hotel y Negocio
-- Añade únicamente lo que no existía; no toca ni renombra nada de lo
-- que ya había (todas las columnas nuevas son opcionales o llevan un
-- default seguro). Ejecutar entero en Supabase → SQL Editor → Run.
-- =====================================================================


-- ---------------------------------------------------------------------
-- Contacto — Apellidos, Número de móvil, y vínculo a Hotel
-- ---------------------------------------------------------------------
alter table contacts add column if not exists last_name text;
alter table contacts add column if not exists mobile_phone text;

-- Vínculo contacto → hotel (independiente del vínculo contacto → empresa
-- que ya existía en contacts_companies). Igual que ese, "many-to-many"
-- en la tabla pero el formulario solo deja elegir un hotel a la vez.
create table if not exists hotels_contacts (
  id         bigint generated by default as identity primary key,
  contact_id bigint not null references contacts(id) on delete cascade,
  hotel_id   bigint not null references hotels(id) on delete cascade
);
create index if not exists idx_hotels_contacts_contact_id on hotels_contacts(contact_id);
create index if not exists idx_hotels_contacts_hotel_id on hotels_contacts(hotel_id);


-- ---------------------------------------------------------------------
-- Hotel (empresa) — ficha comercial del hotel
-- ---------------------------------------------------------------------
alter table hotels add column if not exists num_rooms integer;
alter table hotels add column if not exists adr numeric;
alter table hotels add column if not exists booking_url text;
alter table hotels add column if not exists website_url text;
alter table hotels add column if not exists stars integer;
alter table hotels add column if not exists category text; -- 'Hotel', 'Apartamento', etc.
alter table hotels add column if not exists is_chain boolean not null default false;
alter table hotels add column if not exists pms text;
alter table hotels add column if not exists city text;
alter table hotels add column if not exists postal_code text;
alter table hotels add column if not exists annual_revenue numeric;
alter table hotels add column if not exists timezone text;
alter table hotels add column if not exists description text;


-- ---------------------------------------------------------------------
-- Negocio (deals) — datos de la oferta/contrato
-- ---------------------------------------------------------------------
alter table deals add column if not exists legal_company_name text; -- Nombre de la sociedad
alter table deals add column if not exists legal_business_name text; -- Razón Social
alter table deals add column if not exists registered_address text; -- Domicilio social
alter table deals add column if not exists tax_id text; -- NIF
alter table deals add column if not exists legal_rep_name text; -- Nombre y apellidos del representante legal
alter table deals add column if not exists legal_rep_id text; -- DNI del representante legal
alter table deals add column if not exists contract_signed boolean not null default false;
alter table deals add column if not exists monthly_fee numeric; -- Cuota mensual
alter table deals add column if not exists billing_contact_name text; -- A quién se envía la factura
alter table deals add column if not exists proposal_attachment_url text; -- URL pública en Supabase Storage
alter table deals add column if not exists proposal_attachment_name text; -- Nombre original del archivo


-- ---------------------------------------------------------------------
-- RLS de la tabla nueva (mismo criterio que el resto: acceso completo
-- para cualquier usuario autenticado).
-- ---------------------------------------------------------------------
alter table hotels_contacts enable row level security;
drop policy if exists "authenticated full access" on hotels_contacts;
create policy "authenticated full access" on hotels_contacts for all to authenticated using (true) with check (true);


-- ---------------------------------------------------------------------
-- Storage — bucket para el adjunto de la oferta presentada en Negocio.
-- Bucket público (mismo criterio de acceso simple que el resto de la
-- app: es una herramienta interna, no hay usuarios externos).
-- ---------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('deal-attachments', 'deal-attachments', true)
on conflict (id) do nothing;

drop policy if exists "authenticated full access deal-attachments" on storage.objects;
create policy "authenticated full access deal-attachments" on storage.objects
  for all to authenticated
  using (bucket_id = 'deal-attachments')
  with check (bucket_id = 'deal-attachments');
