-- =====================================================================
-- Panel/Hoteles: "Hoteles con plan" -> "Hoteles cliente"
-- =====================================================================
alter table hotels rename column has_plan to is_client;


-- =====================================================================
-- Negocios: nota rápida con color + modelos de facturación con color
-- =====================================================================
alter table deals add column if not exists quick_note text;
alter table deals add column if not exists quick_note_color text;

alter table billing_models add column if not exists color text;


-- =====================================================================
-- Contactos: listas (selección de contactos guardada con nombre)
-- =====================================================================
create table if not exists contact_lists (
  id         bigint generated by default as identity primary key,
  name       text not null,
  created_by uuid references auth.users(id) default auth.uid(),
  created_at timestamptz not null default now()
);

create table if not exists contact_lists_contacts (
  id         bigint generated by default as identity primary key,
  list_id    bigint not null references contact_lists(id) on delete cascade,
  contact_id bigint not null references contacts(id) on delete cascade
);
create index if not exists idx_contact_lists_contacts_list_id on contact_lists_contacts(list_id);
create index if not exists idx_contact_lists_contacts_contact_id on contact_lists_contacts(contact_id);
-- único sin duplicar el mismo contacto en la misma lista dos veces;
-- también es el índice que usa el "on conflict (list_id, contact_id)"
-- al añadir contactos seleccionados a una lista.
create unique index if not exists idx_contact_lists_contacts_unique on contact_lists_contacts(list_id, contact_id);

alter table contact_lists enable row level security;
drop policy if exists "authenticated full access" on contact_lists;
create policy "authenticated full access" on contact_lists for all to authenticated using (true) with check (true);

alter table contact_lists_contacts enable row level security;
drop policy if exists "authenticated full access" on contact_lists_contacts;
create policy "authenticated full access" on contact_lists_contacts for all to authenticated using (true) with check (true);
